/**
 * MVP Criterion #7 — Search
 *
 * Full-text search returns results filtered by taxonomy, persona, site, language,
 * and publication status.
 *
 * Implementation target: Phase 2 (pgvector + tsvector, see ADR 003)
 * Relevant DB: jv_articles, jv_prayers, jv_music, jv_taxonomy, jv_personas
 */

describe('MVP Criterion 7: Search', () => {
  test.todo(
    'GET /api/search?q=prayer returns articles and prayers containing "prayer"'
  )

  test.todo(
    'GET /api/search?q=grace&type=article returns only Article objects'
  )

  test.todo(
    'GET /api/search?q=faith&taxonomy=evangelism filters results to evangelism subtree'
  )

  test.todo(
    'GET /api/search?q=hope&persona=jubilee returns only content generated by Jubilee persona'
  )

  test.todo(
    'GET /api/search?q=salvation&site=jubileeverse.com returns only content mapped to that site'
  )

  test.todo(
    'GET /api/search?q=grace&language=es returns Spanish-language content'
  )

  test.todo(
    'GET /api/search?q=love&status=published returns only published objects'
  )

  test.todo(
    'GET /api/search?q=love&status=draft returns 403 for unauthenticated users'
  )

  test.todo(
    'Search results include relevance scores and are sorted by score descending'
  )

  test.todo(
    'Semantic search: GET /api/search?q=walking+with+God matches "discipleship" articles'
  )
})
