/**
 * PortalNavPanel.tsx — Left 280px panel: site selector + date-tree nav (Part 4 S7)
 */

import * as React from 'react'
import { ChevronDown, ChevronRight, LayoutDashboard, Loader2 } from 'lucide-react'
import { usePortalSites, usePortalTree, useGenerateSitePortal } from '../../hooks/usePortal'
import type { PortalGridRow } from '../../types/content-objects'

const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

interface PortalNavPanelProps {
  selectedSiteId: number | null
  onSelectSite: (id: number) => void
  selectedDate: string | null
  onSelectDate: (date: string | null) => void
  selectedPortalId: string | null
  onSelectPortal: (id: string) => void
}

export function PortalNavPanel({
  selectedSiteId,
  onSelectSite,
  selectedDate,
  onSelectDate,
  selectedPortalId,
  onSelectPortal,
}: PortalNavPanelProps) {
  const { data: sites = [], isLoading: sitesLoading } = usePortalSites()
  const { data: tree = {}, isLoading: treeLoading } = usePortalTree(selectedSiteId)
  const generateSite = useGenerateSitePortal()

  // Expand state: Set of 'year' or 'year-month' keys
  const [expanded, setExpanded] = React.useState<Set<string>>(new Set())
  // Track whether auto-generate has already been triggered for the current site
  const autoGeneratedRef = React.useRef<number | null>(null)

  // Auto-expand current year/month when tree loads
  const years = Object.keys(tree).sort((a, b) => Number(b) - Number(a))
  React.useEffect(() => {
    if (years.length) {
      const latestYear = years[0]
      const months = Object.keys(tree[latestYear] ?? {}).sort((a, b) => Number(b) - Number(a))
      const latestMonth = months[0]
      setExpanded(new Set([latestYear, `${latestYear}-${latestMonth}`]))
    }
  }, [JSON.stringify(years)]) // eslint-disable-line react-hooks/exhaustive-deps

  // Auto-generate site portal pages when a site is selected and has no pages yet
  React.useEffect(() => {
    if (!selectedSiteId || treeLoading || years.length > 0) return
    if (generateSite.isPending) return
    if (autoGeneratedRef.current === selectedSiteId) return // already tried this site
    autoGeneratedRef.current = selectedSiteId
    generateSite.mutate({ siteId: selectedSiteId })
  }, [selectedSiteId, treeLoading, years.length]) // eslint-disable-line react-hooks/exhaustive-deps

  function toggle(key: string) {
    setExpanded(prev => {
      const next = new Set(prev)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return next
    })
  }

  function handleDayClick(date: string) {
    onSelectDate(selectedDate === date ? null : date)
  }

  // Auto-select first site
  React.useEffect(() => {
    if (!selectedSiteId && sites.length) {
      onSelectSite(sites[0].site_id)
    }
  }, [sites.length]) // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center gap-2 px-3 h-10 border-b shrink-0">
        <LayoutDashboard size={14} className="text-muted-foreground" />
        <span className="text-xs font-medium text-foreground">Portal</span>
      </div>

      {/* Site selector */}
      <div className="px-3 py-2 border-b shrink-0">
        {sitesLoading ? (
          <div className="h-8 bg-muted/40 animate-pulse rounded" />
        ) : (
          <select
            value={selectedSiteId ?? ''}
            onChange={e => onSelectSite(Number(e.target.value))}
            className="w-full text-xs border rounded px-2 h-8 bg-background text-foreground"
          >
            {sites.map(s => (
              <option key={s.site_id} value={s.site_id}>
                {s.site_name ?? `Site ${s.site_id}`}
              </option>
            ))}
            {!sites.length && <option value="">No sites</option>}
          </select>
        )}
      </div>

      {/* Date tree */}
      <div className="flex-1 overflow-y-auto py-1">
        {!selectedSiteId && (
          <p className="px-3 py-4 text-xs text-muted-foreground">Select a site above</p>
        )}
        {selectedSiteId && treeLoading && (
          <div className="space-y-1 px-3 py-2">
            {[...Array(4)].map((_, i) => (
              <div key={i} className="h-6 bg-muted/40 animate-pulse rounded" />
            ))}
          </div>
        )}
        {selectedSiteId && !treeLoading && !years.length && (
          <div className="px-3 py-4 flex items-center gap-2 text-xs text-muted-foreground">
            {generateSite.isPending
              ? <><Loader2 size={12} className="animate-spin shrink-0" /> Generating portal pages…</>
              : generateSite.isError
                ? 'Generation failed — try refreshing'
                : 'Preparing portal pages…'
            }
          </div>
        )}

        {years.map(year => {
          const yearExpanded = expanded.has(year)
          const months = Object.keys(tree[year] ?? {}).sort((a, b) => Number(b) - Number(a))

          return (
            <div key={year}>
              {/* Year row */}
              <button
                className="flex items-center gap-1 w-full px-3 py-1 text-xs font-semibold text-foreground hover:bg-muted/50 transition-colors"
                onClick={() => toggle(year)}
              >
                {yearExpanded ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
                {year}
              </button>

              {yearExpanded && months.map(month => {
                const monthKey = `${year}-${month}`
                const monthExpanded = expanded.has(monthKey)
                const days = Object.keys(tree[year][month] ?? {}).sort((a, b) => Number(b) - Number(a))

                return (
                  <div key={monthKey}>
                    {/* Month row */}
                    <button
                      className="flex items-center gap-1 w-full pl-6 pr-3 py-1 text-xs text-muted-foreground hover:bg-muted/50 transition-colors"
                      onClick={() => toggle(monthKey)}
                    >
                      {monthExpanded ? <ChevronDown size={11} /> : <ChevronRight size={11} />}
                      {MONTH_NAMES[Number(month) - 1]}
                    </button>

                    {monthExpanded && days.map(day => {
                      const date = `${year}-${month}-${day}`
                      const portals: PortalGridRow[] = tree[year][month][day] ?? []
                      const daySelected = selectedDate === date

                      return (
                        <div key={date}>
                          {/* Day row */}
                          <button
                            className={[
                              'flex items-center justify-between w-full pl-10 pr-3 py-1 text-xs transition-colors',
                              daySelected
                                ? 'bg-primary/10 text-primary font-medium'
                                : 'text-foreground hover:bg-muted/50',
                            ].join(' ')}
                            onClick={() => handleDayClick(date)}
                          >
                            <span>{Number(day)}</span>
                            <span className="text-muted-foreground tabular-nums">{portals.length}</span>
                          </button>

                          {/* Portal rows under selected day */}
                          {daySelected && portals.map(portal => (
                            <button
                              key={portal.id}
                              className={[
                                'flex flex-col items-start w-full pl-12 pr-3 py-1 text-xs transition-colors',
                                selectedPortalId === portal.id
                                  ? 'bg-primary/10 text-primary'
                                  : 'text-muted-foreground hover:bg-muted/50 hover:text-foreground',
                              ].join(' ')}
                              onClick={() => onSelectPortal(portal.id)}
                            >
                              <span className="capitalize">{portal.portal_type}</span>
                              {portal.taxonomy_name && (
                                <span className="truncate w-full text-muted-foreground" style={{ fontSize: '10px' }}>
                                  {portal.taxonomy_name}
                                </span>
                              )}
                            </button>
                          ))}
                        </div>
                      )
                    })}
                  </div>
                )
              })}
            </div>
          )
        })}
      </div>
    </div>
  )
}
