/**
 * Prayer dataset — ported verbatim from the original static prayer.html.
 * This is a fixed, client-side catalogue used by the guided-prayer player.
 */

export type PrayerCategory =
  | 'morning'
  | 'evening'
  | 'healing'
  | 'comfort'
  | 'gratitude'
  | 'protection'
  | 'guidance'
  | 'family';

export interface Scripture {
  text: string;
  ref: string;
}

export interface Prayer {
  name: string;
  category: PrayerCategory;
  image: string;
  description: string;
  duration: string;
  author: string;
  scripture: Scripture;
  lines: string[];
}

export const prayers: Prayer[] = [
  {
    name: 'Morning Offering',
    category: 'morning',
    image: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=400&h=400&fit=crop',
    description: 'Begin your day by offering it to the Lord with gratitude and purpose.',
    duration: '2 min',
    author: 'Traditional',
    scripture: {
      text: '“This is the day the LORD has made; let us rejoice and be glad in it.”',
      ref: 'Psalm 118:24',
    },
    lines: [
      'Heavenly Father, I thank You for the gift of this new day.',
      'As the morning light breaks through, I offer this day to You.',
      'Guide my steps, Lord, and let every word I speak bring glory to Your name.',
      'Fill my heart with Your peace that surpasses all understanding.',
      'Help me to see Your hand at work in every moment of this day.',
      'Grant me the strength to face whatever challenges may come,',
      'and the wisdom to make choices that honor You.',
      'May my actions reflect Your love to everyone I encounter.',
      'I surrender my plans and my worries into Your mighty hands.',
      'In Jesus’ name, I pray. Amen.',
    ],
  },
  {
    name: 'Prayer for Strength',
    category: 'morning',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=400&fit=crop',
    description: 'Ask the Lord for strength to face the day ahead with courage.',
    duration: '2 min',
    author: 'Traditional',
    scripture: {
      text: '“I can do all things through Christ who strengthens me.”',
      ref: 'Philippians 4:13',
    },
    lines: [
      'Lord God Almighty, I come before You this morning seeking Your strength.',
      'You are my rock and my fortress, my shield and my deliverer.',
      'When I feel weak, remind me that Your power is made perfect in weakness.',
      'Give me the courage to stand firm in my faith,',
      'even when the world around me seems uncertain.',
      'Strengthen my body, renew my mind, and fortify my spirit.',
      'Help me to run the race set before me with perseverance,',
      'keeping my eyes fixed on You, the author and perfecter of my faith.',
      'Let Your strength flow through me today, Lord.',
      'In the mighty name of Jesus, Amen.',
    ],
  },
  {
    name: 'Evening Reflection',
    category: 'evening',
    image: 'https://images.unsplash.com/photo-1507400492013-162706c8c05e?w=400&h=400&fit=crop',
    description: "End your day reflecting on God's faithfulness and grace.",
    duration: '3 min',
    author: 'Traditional',
    scripture: {
      text: '“In peace I will lie down and sleep, for you alone, LORD, make me dwell in safety.”',
      ref: 'Psalm 4:8',
    },
    lines: [
      'Dear Lord, as this day comes to a close, I pause to reflect on Your goodness.',
      'Thank You for every blessing You poured out today,',
      'both the ones I noticed and the ones I overlooked.',
      'Forgive me for the moments when I fell short of Your grace.',
      'Where I spoke harshly, bring healing. Where I acted selfishly, bring restoration.',
      'I release the worries and burdens of this day into Your hands.',
      'Guard my mind from anxious thoughts as I prepare for rest.',
      'Cover my home and loved ones with Your protective wings.',
      'Let me sleep in the peace that only You can give,',
      'and awaken me tomorrow refreshed and ready to serve You.',
      'Watch over me through the night, Father.',
      'In Jesus’ precious name, Amen.',
    ],
  },
  {
    name: 'Bedtime Prayer',
    category: 'evening',
    image: 'https://images.unsplash.com/photo-1532767153582-b1a0e5145009?w=400&h=400&fit=crop',
    description: "A gentle prayer to close the night in God's comforting presence.",
    duration: '2 min',
    author: 'Traditional',
    scripture: {
      text: '“He who watches over Israel will neither slumber nor sleep.”',
      ref: 'Psalm 121:4',
    },
    lines: [
      'Father in Heaven, the day is done and night has come.',
      'I lay down my burdens at the foot of the cross.',
      'Thank You for carrying me through another day.',
      'As I close my eyes, let me feel Your presence beside me.',
      'Calm my restless thoughts and quiet my soul.',
      'Send Your angels to keep watch over my household.',
      'Let the rhythm of my breathing remind me of Your steady love.',
      'Grant me restful sleep and peaceful dreams.',
      'And when morning comes, let me rise with joy in my heart.',
      'Goodnight, Lord. I trust You with everything. Amen.',
    ],
  },
  {
    name: 'Prayer for Healing',
    category: 'healing',
    image: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=400&h=400&fit=crop',
    description: "Seek the Lord's healing touch for body, mind, and spirit.",
    duration: '3 min',
    author: 'Traditional',
    scripture: {
      text: '“He heals the brokenhearted and binds up their wounds.”',
      ref: 'Psalm 147:3',
    },
    lines: [
      'Merciful Father, I come to You as the Great Physician.',
      'You formed my body, and You alone have the power to restore it.',
      'I ask for Your healing hand to touch every area of pain and sickness.',
      'Lord, heal me physically — restore health to my body.',
      'Heal me emotionally — mend the wounds that others cannot see.',
      'Heal me spiritually — draw me closer to You through this trial.',
      'I believe that by Your stripes, I am healed.',
      'Remove every fear and doubt that tries to steal my hope.',
      'Fill me with the faith to trust Your perfect timing.',
      'Whether You heal in an instant or through a journey,',
      'I will praise You, for You are good in all You do.',
      'In the healing name of Jesus Christ, Amen.',
    ],
  },
  {
    name: 'Prayer for the Sick',
    category: 'healing',
    image: 'https://images.unsplash.com/photo-1459862515011-816c1b41d9a2?w=400&h=400&fit=crop',
    description: 'Intercede on behalf of someone who is suffering from illness.',
    duration: '2 min',
    author: 'Traditional',
    scripture: {
      text: '“The LORD sustains them on their sickbed and restores them from their bed of illness.”',
      ref: 'Psalm 41:3',
    },
    lines: [
      'Loving God, I lift up to You those who are battling illness.',
      'You see their suffering and You know their every need.',
      'Place Your healing hand upon them and restore their strength.',
      'Give their doctors wisdom and their caregivers compassion.',
      'Surround them with Your comfort when the nights are long.',
      'Remind them that they are not alone, for You are with them.',
      'Renew their hope and give them patience in their recovery.',
      'Lord, let Your will be done, and let them feel Your love.',
      'In the powerful name of Jesus, I pray. Amen.',
    ],
  },
  {
    name: 'Prayer for Comfort',
    category: 'comfort',
    image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=400&h=400&fit=crop',
    description: 'Find solace and peace in the arms of the Lord during difficult times.',
    duration: '3 min',
    author: 'Traditional',
    scripture: {
      text: '“Blessed are those who mourn, for they will be comforted.”',
      ref: 'Matthew 5:4',
    },
    lines: [
      'O Lord, my Comforter, I come to You with a heavy heart.',
      'The weight of this season feels like more than I can bear.',
      'But You have promised that You are near to the brokenhearted,',
      'and that You save those who are crushed in spirit.',
      'Wrap me in Your everlasting arms and hold me close.',
      'Let Your peace, which surpasses all understanding,',
      'guard my heart and mind in Christ Jesus.',
      'When tears fall, catch them in Your hands.',
      'When grief overwhelms, be my steady anchor.',
      'I trust that You are working all things together for good,',
      'even when I cannot see the way forward.',
      'Carry me, Lord, until I can walk again.',
      'In Jesus’ comforting name, Amen.',
    ],
  },
  {
    name: 'Prayer in Times of Grief',
    category: 'comfort',
    image: 'https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=400&h=400&fit=crop',
    description: 'A prayer for those walking through the valley of loss and sorrow.',
    duration: '3 min',
    author: 'Traditional',
    scripture: {
      text: '“Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me.”',
      ref: 'Psalm 23:4',
    },
    lines: [
      'Heavenly Father, my heart is broken with grief.',
      'The loss I carry feels unbearable, and the emptiness is so deep.',
      'But even in my darkest hour, I know You are with me.',
      'You are the God who weeps with us and holds us in our sorrow.',
      'Help me to grieve with hope — the hope that death is not the end.',
      'Remind me of Your promise of eternal life through Jesus Christ.',
      'Comfort me with the assurance that my loved one is at peace in Your presence.',
      'When the waves of sadness threaten to pull me under,',
      'be my lifeline and pull me back to solid ground.',
      'Give me the strength to take one more step, one more breath.',
      'Surround me with people who bring Your light into my darkness.',
      'In time, Lord, turn my mourning into dancing.',
      'Until then, simply hold me. In Jesus’ name, Amen.',
    ],
  },
  {
    name: 'Prayer of Thanksgiving',
    category: 'gratitude',
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=400&fit=crop',
    description: "Express your heartfelt gratitude for God's abundant blessings.",
    duration: '2 min',
    author: 'Traditional',
    scripture: {
      text: '“Give thanks to the LORD, for he is good; his love endures forever.”',
      ref: 'Psalm 107:1',
    },
    lines: [
      'Gracious God, I come with a heart overflowing with gratitude.',
      'You have blessed me beyond what I deserve.',
      'Thank You for the breath in my lungs and the beating of my heart.',
      'Thank You for the people You’ve placed in my life,',
      'who love me and walk beside me on this journey.',
      'Thank You for provision — for daily bread and shelter and warmth.',
      'Thank You for Your Word, which is a lamp to my feet.',
      'Most of all, thank You for the gift of salvation through Jesus Christ.',
      'Help me never to take Your blessings for granted.',
      'Let gratitude be my constant companion. Amen.',
    ],
  },
  {
    name: 'Psalm of Praise',
    category: 'gratitude',
    image: 'https://images.unsplash.com/photo-1508963493744-76fce69379c0?w=400&h=400&fit=crop',
    description: 'Lift your voice in praise and adoration of the Most High God.',
    duration: '2 min',
    author: 'Traditional',
    scripture: {
      text: '“Let everything that has breath praise the LORD.”',
      ref: 'Psalm 150:6',
    },
    lines: [
      'Lord God Almighty, I lift my voice in praise to You!',
      'You are worthy of all honor and all glory.',
      'The heavens declare Your splendor and the earth sings of Your majesty.',
      'From the rising of the sun to its setting, Your name is to be praised.',
      'You are the Alpha and the Omega, the Beginning and the End.',
      'Your love never fails, Your mercy is new every morning.',
      'I praise You for who You are — holy, righteous, faithful, and true.',
      'Let my life be a living praise offering to You.',
      'Hallelujah! Blessed be the name of the Lord! Amen.',
    ],
  },
  {
    name: 'Prayer for Protection',
    category: 'protection',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&h=400&fit=crop',
    description: 'Ask God to shield you and your loved ones from harm.',
    duration: '2 min',
    author: 'Traditional',
    scripture: {
      text: '“The LORD is my light and my salvation — whom shall I fear?”',
      ref: 'Psalm 27:1',
    },
    lines: [
      'Mighty God, I come to You seeking Your divine protection.',
      'You are my fortress, my refuge, and my strong tower.',
      'Shield me from the arrows of the enemy,',
      'and guard my heart from every scheme of darkness.',
      'Place a hedge of protection around my home, my family, and my life.',
      'Send Your angels to stand guard over us day and night.',
      'When danger lurks, be my warning. When evil threatens, be my shield.',
      'I will not fear, for You are with me.',
      'No weapon formed against me shall prosper.',
      'I rest securely in the shadow of Your wings.',
      'In the protective name of Jesus, Amen.',
    ],
  },
  {
    name: 'Armor of God Prayer',
    category: 'protection',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=400&h=400&fit=crop',
    description: 'Put on the full armor of God to stand against spiritual warfare.',
    duration: '3 min',
    author: 'Based on Ephesians 6:10-18',
    scripture: {
      text: '“Put on the full armor of God, so that you can take your stand against the devil’s schemes.”',
      ref: 'Ephesians 6:11',
    },
    lines: [
      'Lord, I put on the full armor of God today.',
      'I fasten the belt of truth around my waist —',
      'let me walk in honesty and integrity in all I do.',
      'I put on the breastplate of righteousness —',
      'guard my heart with Your purity and justice.',
      'I fit my feet with the readiness that comes from the gospel of peace —',
      'let me carry Your good news wherever I go.',
      'I take up the shield of faith —',
      'with it, I will extinguish every flaming arrow of the evil one.',
      'I put on the helmet of salvation —',
      'protect my mind and fill my thoughts with Your truth.',
      'I take up the sword of the Spirit, which is the Word of God —',
      'Your Word is my weapon and my strength.',
      'I pray in the Spirit on all occasions, with all kinds of prayers.',
      'I am dressed for battle and standing firm. In Jesus’ name, Amen.',
    ],
  },
  {
    name: 'Prayer for Wisdom',
    category: 'guidance',
    image: 'https://images.unsplash.com/photo-1456428746267-a1756408f782?w=400&h=400&fit=crop',
    description: "Seek God's wisdom and direction for the decisions ahead.",
    duration: '2 min',
    author: 'Traditional',
    scripture: {
      text: '“If any of you lacks wisdom, you should ask God, who gives generously to all.”',
      ref: 'James 1:5',
    },
    lines: [
      'All-knowing God, I stand at a crossroads and I need Your guidance.',
      'Your Word promises that if I ask for wisdom, You will give it generously.',
      'So I ask, Lord — open my eyes to see the path You’ve prepared.',
      'Silence the noise of the world and help me hear Your still, small voice.',
      'Give me discernment to know what is true, noble, right, and pure.',
      'When I am confused, bring clarity. When I am afraid, bring courage.',
      'Lead me not by my own understanding,',
      'but help me to trust in You with all my heart.',
      'Direct my steps according to Your perfect will.',
      'In the name of Jesus, who is the Way, the Truth, and the Life, Amen.',
    ],
  },
  {
    name: 'Prayer for Direction',
    category: 'guidance',
    image: 'https://images.unsplash.com/photo-1510797215324-95aa89f43c33?w=400&h=400&fit=crop',
    description: "When you're unsure of the way forward, ask God to light the path.",
    duration: '2 min',
    author: 'Traditional',
    scripture: {
      text: '“Your word is a lamp for my feet, a light on my path.”',
      ref: 'Psalm 119:105',
    },
    lines: [
      'Lord, I feel lost and uncertain about which way to go.',
      'The road ahead is unclear, and I need Your light to guide me.',
      'You know the plans You have for me — plans to prosper and not to harm.',
      'Help me to be patient as I wait for Your direction.',
      'Close every door that is not of You,',
      'and open wide the doors You want me to walk through.',
      'Give me the faith to take the first step,',
      'even when I cannot see the whole staircase.',
      'I choose to follow You, Lord, wherever You lead.',
      'In Jesus’ faithful name, Amen.',
    ],
  },
  {
    name: 'Prayer for My Family',
    category: 'family',
    image: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=400&h=400&fit=crop',
    description: 'Lift your family into the loving and protective hands of the Lord.',
    duration: '3 min',
    author: 'Traditional',
    scripture: {
      text: '“As for me and my household, we will serve the LORD.”',
      ref: 'Joshua 24:15',
    },
    lines: [
      'Dear Lord, I bring my family before Your throne of grace.',
      'You are the God who knit us together and called us a family.',
      'I pray for unity — bind us together with cords of love that cannot be broken.',
      'I pray for protection — keep each member safe under Your watchful eye.',
      'I pray for health — strengthen our bodies and guard our minds.',
      'I pray for wisdom — help us make decisions that honor You.',
      'Where there is conflict, bring reconciliation.',
      'Where there is distance, bridge the gap with Your love.',
      'Bless our home and let it be a place of peace, joy, and worship.',
      'May the love of Christ be the foundation on which our family stands.',
      'Raise our children in the knowledge and love of Jesus.',
      'In His precious name, we pray. Amen.',
    ],
  },
  {
    name: 'Prayer for My Children',
    category: 'family',
    image: 'https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=400&h=400&fit=crop',
    description: "A parent's prayer for the protection and spiritual growth of their children.",
    duration: '3 min',
    author: 'Traditional',
    scripture: {
      text: '“Train up a child in the way he should go; even when he is old he will not depart from it.”',
      ref: 'Proverbs 22:6',
    },
    lines: [
      'Father God, my children are the greatest gift You have given me.',
      'I entrust them to Your care, for they belong to You.',
      'Protect them from every danger, seen and unseen.',
      'Guard their hearts from the lies of the enemy.',
      'Plant seeds of faith deep within their souls,',
      'and let those seeds grow into a mighty, unshakeable faith.',
      'Give them friends who will encourage them in righteousness.',
      'Help them to be kind, brave, honest, and compassionate.',
      'When they face temptation, give them the strength to resist.',
      'When they stumble, be quick to catch them and set them upright.',
      'Lord, let them know how deeply they are loved — by me and by You.',
      'Guide them all the days of their lives.',
      'In Jesus’ name, Amen.',
    ],
  },
  {
    name: 'Prayer for Peace',
    category: 'comfort',
    image: 'https://images.unsplash.com/photo-1499002238440-d264edd596ec?w=400&h=400&fit=crop',
    description: 'Ask the Prince of Peace to calm every storm within and around you.',
    duration: '2 min',
    author: 'Traditional',
    scripture: {
      text: '“Peace I leave with you; my peace I give you. I do not give to you as the world gives.”',
      ref: 'John 14:27',
    },
    lines: [
      'Prince of Peace, I desperately need Your calming presence.',
      'My mind is racing and my heart is anxious.',
      'Speak “Peace, be still” over every storm in my life.',
      'Replace my worry with worship and my fear with faith.',
      'Help me to cast all my cares upon You, for You care for me.',
      'Let Your peace, which transcends all understanding,',
      'stand guard over my heart and mind.',
      'Quiet the chaos and let me rest in Your sovereignty.',
      'You are in control, and that is enough.',
      'In the peaceful name of Jesus, Amen.',
    ],
  },
  {
    name: "The Lord's Prayer",
    category: 'morning',
    image: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=400&h=400&fit=crop',
    description: 'The prayer that Jesus taught His disciples, a model for all prayer.',
    duration: '1 min',
    author: 'Jesus Christ (Matthew 6:9-13)',
    scripture: {
      text: '“This, then, is how you should pray.”',
      ref: 'Matthew 6:9',
    },
    lines: [
      'Our Father, who art in heaven, hallowed be Thy name.',
      'Thy kingdom come, Thy will be done,',
      'on earth as it is in heaven.',
      'Give us this day our daily bread,',
      'and forgive us our trespasses,',
      'as we forgive those who trespass against us.',
      'And lead us not into temptation,',
      'but deliver us from evil.',
      'For Thine is the kingdom, and the power,',
      'and the glory, forever and ever.',
      'Amen.',
    ],
  },
  {
    name: 'Serenity Prayer',
    category: 'guidance',
    image: 'https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=400&h=400&fit=crop',
    description: 'A beloved prayer for acceptance, courage, and wisdom.',
    duration: '1 min',
    author: 'Reinhold Niebuhr',
    scripture: {
      text: '“Trust in the LORD with all your heart and lean not on your own understanding.”',
      ref: 'Proverbs 3:5',
    },
    lines: [
      'God, grant me the serenity to accept the things I cannot change,',
      'the courage to change the things I can,',
      'and the wisdom to know the difference.',
      'Living one day at a time, enjoying one moment at a time.',
      'Accepting hardship as a pathway to peace.',
      'Taking, as Jesus did, this sinful world as it is,',
      'not as I would have it.',
      'Trusting that You will make all things right',
      'if I surrender to Your will.',
      'That I may be reasonably happy in this life',
      'and supremely happy with You forever in the next.',
      'Amen.',
    ],
  },
  {
    name: 'Prayer of St. Francis',
    category: 'guidance',
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=400&h=400&fit=crop',
    description: 'Make me an instrument of Your peace — a timeless prayer of service.',
    duration: '2 min',
    author: 'Attributed to St. Francis of Assisi',
    scripture: {
      text: '“Blessed are the peacemakers, for they will be called children of God.”',
      ref: 'Matthew 5:9',
    },
    lines: [
      'Lord, make me an instrument of Your peace.',
      'Where there is hatred, let me sow love.',
      'Where there is injury, pardon.',
      'Where there is doubt, faith.',
      'Where there is despair, hope.',
      'Where there is darkness, light.',
      'Where there is sadness, joy.',
      'O Divine Master, grant that I may not so much seek',
      'to be consoled as to console,',
      'to be understood as to understand,',
      'to be loved as to love.',
      'For it is in giving that we receive,',
      'it is in pardoning that we are pardoned,',
      'and it is in dying that we are born to eternal life.',
      'Amen.',
    ],
  },
];

const CATEGORY_LABELS: Record<PrayerCategory, string> = {
  morning: 'Morning',
  evening: 'Evening',
  healing: 'Healing',
  comfort: 'Comfort',
  gratitude: 'Gratitude',
  protection: 'Protection',
  guidance: 'Guidance',
  family: 'Family',
};

export function getCategoryLabel(cat: PrayerCategory): string {
  return CATEGORY_LABELS[cat] ?? cat;
}

export const FILTER_CATEGORIES: PrayerCategory[] = [
  'morning',
  'evening',
  'healing',
  'comfort',
  'gratitude',
  'guidance',
  'protection',
  'family',
];

/** Indices used by the desktop "Most Popular" / "Recommended" rails. */
export const POPULAR_INDICES = [17, 0, 4, 6]; // Lord's Prayer, Morning Offering, Healing, Comfort
export const RECOMMENDED_INDICES = [11, 19, 8, 14]; // Armor of God, St. Francis, Thanksgiving, My Family

/** Indices used by the mobile accordion rails. */
export const MOBILE_POPULAR_INDICES = [0, 1, 2, 3];
export const MOBILE_RECOMMENDED_INDICES = [4, 6, 8, 10];

export const FAVORITES_STORAGE_KEY = 'jubilee_prayer_favorites';
