/**
 * PubOS Unified Content Object Types — Phase 3
 *
 * Single canonical content object model with UUID PK and type-specific
 * extension_data JSONB. All Phase 3 content APIs use these types.
 *
 * See docs/adr/002-database.md for schema rationale.
 * See server.js jv_content_objects table for the authoritative DB schema.
 */

// ── Object Type & Status Enums ────────────────────────────────────────────────

export type ObjectType =
  | 'article'
  | 'prayer'
  | 'music'
  | 'radio_episode'
  | 'podcast'
  | 'image'
  | 'video'
  | 'author'
  | 'page_template'
  | 'asset'
  | 'prompt_recipe'
  | 'site'

export const OBJECT_TYPES: ObjectType[] = [
  'article', 'prayer', 'music', 'radio_episode', 'podcast',
  'image', 'video', 'author', 'page_template', 'asset', 'prompt_recipe', 'site',
]

export type ObjectStatus =
  | 'draft'
  | 'review'
  | 'internal_audit'
  | 'additional_work'
  | 'pending_review'
  | 'approved'
  | 'scheduled'
  | 'published'
  | 'archived'

export const OBJECT_STATUSES: ObjectStatus[] = [
  'draft', 'review', 'internal_audit', 'additional_work', 'pending_review',
  'approved', 'scheduled', 'published', 'archived',
]

// ── Base Content Object ───────────────────────────────────────────────────────

export interface ContentObject {
  /** UUID primary key generated by PostgreSQL gen_random_uuid() */
  id: string
  object_type: ObjectType
  title: string | null
  /** URL-safe identifier, unique within (object_type) scope */
  slug: string | null
  summary: string | null
  status: ObjectStatus
  /** BCP-47 language tag, e.g. en-US, es-MX */
  language: string
  created_by: string | null
  updated_by: string | null
  published_at: string | null
  scheduled_at: string | null
  archived_at: string | null
  /** Incrementing version number starting at 1 */
  version: number
  /** Type-specific fields; see extension interfaces below */
  extension_data: Record<string, unknown>
  /** SEO metadata, OG tags, structured data hints */
  meta_data: ContentMetaData
  /** Object-level permission overrides */
  permissions: Record<string, unknown>
  /** Phase 8: Cross-site publish targets */
  publish_targets?: SitePublishTarget[]
  created_at: string
  updated_at: string
}

// ── Meta Data ─────────────────────────────────────────────────────────────────

export interface ContentMetaData {
  seo_title?: string
  seo_description?: string
  og_image?: string
  og_type?: string
  canonical_url?: string
  structured_data?: Record<string, unknown>
  [key: string]: unknown
}

// ── Type-Specific Extension Schemas ──────────────────────────────────────────

/** 3.2.1 Article extension_data */
export interface ArticleExtension {
  body_html: string
  body_markdown?: string
  word_count: number
  reading_time_minutes: number
  featured_image_id?: string
  author_ids: string[]
  table_of_contents?: Array<{ level: number; text: string; id: string }>
}

/** 3.2.2 Prayer extension_data */
export interface ScriptureRef {
  book: string
  chapter: number
  verse_start: number
  verse_end?: number
  translation: string
}

export interface PrayerExtension {
  prayer_text: string
  scripture_refs: ScriptureRef[]
  occasion_type: string
  liturgical_season?: string
  responsive_format: boolean
}

/** 3.2.3 Music extension_data */
export interface MusicExtension {
  lyrics_text: string
  chord_chart?: string
  audio_asset_id?: string
  bpm?: number
  key_signature?: string
  album_id?: string
  ccli_number?: string
}

/** 3.2.4 Radio Episode extension_data */
export interface SegmentMarker {
  start_seconds: number
  end_seconds?: number
  label: string
}

export interface RadioEpisodeExtension {
  script_text: string
  show_notes?: string
  audio_asset_id?: string
  episode_number?: number
  series_id?: string
  duration_seconds?: number
  segments: SegmentMarker[]
}

/** Asset extension_data (S3 storage) */
export interface AssetExtension {
  storage_key: string
  public_url: string
  filename?: string
  content_type?: string
  file_size?: number
  width?: number
  height?: number
  duration_seconds?: number
}

// ── Revision History ──────────────────────────────────────────────────────────

export interface ContentRevision {
  id: number
  content_object_id: string
  /** Legacy polymorphic reference — may be present for Phase 1 table revisions */
  object_table?: string
  object_id?: number
  version: number
  /** Full snapshot of the content object at this version */
  snapshot: ContentObject
  change_summary: string | null
  changed_by: string | null
  changed_at: string
}

// ── Audit Log ─────────────────────────────────────────────────────────────────

export type AuditEventType =
  | 'content.created'
  | 'content.updated'
  | 'content.status_changed'
  | 'content.published'
  | 'content.archived'
  | 'content.deleted'
  | 'content.rolled_back'
  | 'taxonomy.node_created'
  | 'taxonomy.node_moved'
  | 'user.login'
  | 'user.permission_changed'
  | 'site.config_changed'
  | 'ai.generation_requested'
  | 'ai.generation_completed'

export interface AuditLogEntry {
  id: number
  event_type: AuditEventType | string
  actor_id: string | null
  target_type: string | null
  target_id: string | null
  details: Record<string, unknown>
  ip_address: string | null
  user_agent: string | null
  created_at: string
}

// ── API Request / Response Types ──────────────────────────────────────────────

export interface CreateContentObjectRequest {
  object_type: ObjectType
  title?: string
  slug?: string
  summary?: string
  status?: ObjectStatus
  language?: string
  /** Legacy single-author shorthand; server converts to jv_content_author_map entry */
  author_id?: string
  /** Multi-author attributions */
  authors?: Array<{ author_id: string; role: ContentAuthorRole; display_order: number }>
  extension_data?: Record<string, unknown>
  meta_data?: Partial<ContentMetaData>
  permissions?: Record<string, unknown>
}

export interface UpdateContentObjectRequest {
  title?: string
  slug?: string
  summary?: string
  status?: ObjectStatus
  language?: string
  extension_data?: Record<string, unknown>
  meta_data?: Partial<ContentMetaData>
  permissions?: Record<string, unknown>
  change_summary?: string
}

export interface ContentListResponse {
  items: ContentObject[]
  total: number
  limit: number
  offset: number
}

export interface ContentSearchFacets {
  type: Record<string, number>
  status: Record<string, number>
  language: Record<string, number>
}

export interface ContentSearchResponse {
  items: ContentObject[]
  total: number
  limit: number
  offset: number
  facets: ContentSearchFacets
}

export interface ContentDiffResponse {
  from: number
  to: number
  diff: Record<string, { from: unknown; to: unknown }>
}

export interface AssetUploadUrlRequest {
  filename: string
  content_type: string
  object_type?: ObjectType
}

export interface AssetUploadUrlResponse {
  uploadUrl: string
  publicUrl: string
  key: string
  uuid: string
}

export interface AssetConfirmRequest {
  key: string
  public_url: string
  filename?: string
  content_type?: string
  file_size?: number
  title?: string
  object_type?: ObjectType
}

export interface AuditLogResponse {
  items: AuditLogEntry[]
  total: number
}

// ── Phase 5: Workflow ────────────────────────────────────────────────────────
export interface WorkflowTransitionRequest {
  to_status: ObjectStatus
  reason?: string        // required for review→draft
  scheduled_at?: string  // required for approved→scheduled (ISO timestamp)
}

// Client-side transition map: which transitions each role can initiate
export const CLIENT_WORKFLOW_TRANSITIONS: Partial<Record<ObjectStatus,
    Partial<Record<string, ObjectStatus[]>>>> = {
  draft:     { editor: ['review'], admin: ['review'], site_owner: ['review'] },
  review:    { reviewer: ['draft', 'approved'], admin: ['draft', 'approved'], site_owner: ['draft', 'approved'] },
  approved:  { publisher: ['scheduled', 'published'], admin: ['scheduled', 'published', 'draft'], site_owner: ['scheduled', 'published'] },
  scheduled: { publisher: ['published', 'draft'], admin: ['published', 'draft'], site_owner: ['published', 'draft'] },
  published: { publisher: ['archived'], admin: ['archived', 'draft'], site_owner: ['archived'] },
  archived:  { editor: ['draft'], admin: ['draft'], site_owner: ['draft'] },
}

// ── Phase 5: Notifications ───────────────────────────────────────────────────
export interface Notification {
  id: number
  recipient_id: string
  type: 'status_change' | 'comment_mention' | 'task_assigned' | 'published'
  title: string
  body: string | null
  object_type: string | null
  object_id: string | null
  read: boolean
  created_at: string
}

// ── Phase 5: Tasks ───────────────────────────────────────────────────────────
export type TaskStatus = 'open' | 'in_progress' | 'completed'

export interface ContentTask {
  id: number
  content_object_id: string
  title: string
  description: string | null
  status: TaskStatus
  assignee_id: string
  created_by: string
  created_at: string
  updated_at: string
  completed_at: string | null
}

export interface CreateTaskRequest {
  title: string
  description?: string
  assignee_id: string
}

export interface UpdateTaskRequest {
  title?: string
  description?: string
  status?: TaskStatus
}

// ── Phase 5: Presence ────────────────────────────────────────────────────────
export interface PresenceUser {
  email: string
  role: string
}

// ── Phase 6: AI Generation ────────────────────────────────────────────────────

export interface PromptVariable {
  name:           string
  source:         'taxonomy_context' | 'author_profile' | 'editor_input' | 'system_computed' | 'job_parameter'
  required:       boolean
  default_value?: string
  description?:   string
}

export interface PromptRecipeExtension {
  system_prompt:            string
  user_template:            string
  target_content_type:      ObjectType
  model?:                   string
  max_tokens?:              number
  constraints?: {
    max_length?:               number
    min_length?:               number
    required_sections?:        string[]
    forbidden_topics?:         string[]
    required_scripture_count?: number
  }
  // Section 5 additions
  variables?:               PromptVariable[]
  output_schema?:           Record<string, unknown>
  post_processors?:         string[]
  author_id?:               string | null
  applicable_site_ids?:     string[]
  language_context?:        string
  audience_scope_node_ids?: number[]
}

export interface GenerateRequest {
  recipe_slug:          string
  object_type:          ObjectType
  taxonomy_node_id?:    number | null
  language?:            string
  author_id?:           string | null
  source_object_id?:    string | null
  custom_instructions?: string | null
  confirmed?:           boolean
}

export interface SafetyFlag {
  rule:     string
  severity: 'warn' | 'block'
  message:  string
}

export interface GenerateResponse {
  content_object: ContentObject
  log_id:         string
  safety_flags:   SafetyFlag[]
}

export interface PromptRecipeSummary {
  id:                  string
  slug:                string
  title:               string | null
  summary:             string | null
  target_content_type: string | null
  constraints:         PromptRecipeExtension['constraints'] | null
  created_at:          string
}

export interface GenerationLogEntry {
  id:               string
  actor_id:         string
  recipe_slug:      string
  object_type:      string
  taxonomy_node_id: number | null
  status:           'pending' | 'completed' | 'failed' | 'flagged'
  result_object_id: string | null
  safety_flags:     SafetyFlag[]
  input_tokens:     number | null
  output_tokens:    number | null
  duration_ms:      number | null
  requested_at:     string
  completed_at:     string | null
  error_message:    string | null
}

export interface GenerationLogResponse {
  items:  GenerationLogEntry[]
  total:  number
  limit:  number
  offset: number
}

// ── Phase 7: Author Management ────────────────────────────────────────────────

export interface VoiceProfile {
  tone?:                  string
  vocabulary_level?:      string
  sentence_style?:        string
  theological_tradition?: string
}

export interface AuthorExampleOutput {
  content_type:  string
  sample_text:   string
  context_note?: string
}

export interface AuthorExtension {
  display_name?:      string
  canonical_slug?:    string
  avatar_asset_id?:   string | null
  avatar_url?:        string | null  // cached public URL for display
  social_links?:      { twitter?: string; instagram?: string; linkedin?: string; website?: string }
  default_language?:  string
  voice_profile?:     VoiceProfile
  mission_statement?: string
  boundaries?:        string[]
  example_outputs?:   AuthorExampleOutput[]
  is_active?:         boolean
  model?:             string
  max_chat_tokens?:   number
  /** Taxonomy group for the author hierarchy tree */
  author_group?:      'inspire_family' | 'contributing' | 'ministers'
  /** Role/title displayed under the author's name */
  role?:              string
}

// ── Author Bios (Section 5 — DB-backed, normalized) ───────────────────────────

export interface AuthorBio {
  id:          string
  author_id:   string
  channel:     string
  bio_text:    string
  bio_short:   string | null
  word_count:  number
  language:    string
  is_primary:  boolean
  version:     number
  created_at:  string
  updated_at:  string
  updated_by:  string | null
}

export interface CreateAuthorBioRequest {
  channel:    string
  bio_text:   string
  bio_short?: string
  language?:  string
  is_primary?: boolean
}

export interface UpdateAuthorBioRequest {
  bio_text?:   string
  bio_short?:  string
  language?:   string
  is_primary?: boolean
}

// ── Content Author Attribution (Section 6 — junction table) ───────────────────

export type ContentAuthorRole =
  | 'primary_author'
  | 'contributor'
  | 'editor'
  | 'translator'
  | 'narrator'

export interface ContentAuthorAttribution {
  id:                 string
  content_object_id:  string
  author_id:          string
  role:               ContentAuthorRole
  display_order:      number
  attributed_at:      string
  attributed_by:      string | null
  /** Hydrated fields from author content object */
  display_name?:      string | null
  canonical_slug?:    string | null
  avatar_asset_id?:   string | null
}

export interface AuthorChatMessage {
  role:      'user' | 'assistant'
  content:   string
  timestamp: string
}

export interface AuthorChatResponse {
  response:      string
  session_id:    number
  message_count: number
}

export interface AuthorUsageEntry {
  author_id:          string
  author_name:        string | null
  taxonomy_node_id:   number | null
  node_name:          string | null
  node_slug:          string | null
  content_count:      number
  ai_generated_count: number
  last_used_at:       string
}

export interface CreateAuthorRequest {
  title:          string
  summary?:       string
  status?:        ObjectStatus
  extension_data: AuthorExtension
}

export interface UpdateAuthorRequest {
  title?:          string
  summary?:        string
  status?:         ObjectStatus
  extension_data?: AuthorExtension
}

// ── Phase 8: Multi-Site Registry & Cross-Site Publishing ──────────────────────

export type SitePublishTargetStatus = 'pending' | 'published' | 'unpublished'

export interface SiteOverrides {
  title?:             string | null
  summary?:           string | null
  cta_text?:          string | null
  cta_url?:           string | null
  featured_image_id?: string | null
}

export interface SitePublishTarget {
  site_id:        string
  status:         SitePublishTargetStatus
  overrides?:     SiteOverrides
  published_url?: string | null
  published_at?:  string | null
}

export interface PublishRules {
  auto_publish?:                boolean
  require_site_owner_approval?: boolean
  content_type_whitelist?:      string[]
  blackout_dates?:              string[]
}

export interface TaxonomyMapping {
  root_ids?: number[]
}

export interface SiteExtension {
  domain?:               string
  alternate_domains?:    string[]
  theme_id?:             string | null
  nav_mapping?:          Record<string, unknown>
  taxonomy_mapping?:     TaxonomyMapping
  publishing_rules?:     PublishRules
  template_assignments?: Record<string, unknown>
  site_tone?:            string
  analytics_config?:     Record<string, unknown>
  // S13 config editor fields:
  primary_brand_color?:         string
  logo_url?:                    string
  favicon_url?:                 string
  custom_css?:                  string
  homepage_portal_behavior?:    'auto_generate_daily' | 'manual_curation' | 'featured_taxonomy_mix'
  nav_layout?:                  'top-bar' | 'side-nav' | 'mega-menu'
  max_taxonomy_assignments?:    number
  footer_html?:                 string
  api_base_url?:                string
  cdn_url?:                     string
  cache_ttl?:                   number
  enable_service_worker?:       boolean
  feature_flags?:               Record<string, boolean | string>
  ga_id?:                       string
  fb_pixel_id?:                 string
  custom_analytics_script?:     string
  portal_rules?:                Record<string, unknown>
}

export interface CreateSiteRequest {
  title:          string
  summary?:       string
  status?:        ObjectStatus
  extension_data: SiteExtension
}

export interface UpdateSiteRequest {
  title?:          string
  summary?:        string
  status?:         ObjectStatus
  extension_data?: SiteExtension
}

export interface SitePublishingReportEntry {
  site_id:           string
  site_title:        string
  domain:            string | null
  published_count:   number
  pending_count:     number
  last_published_at: string | null
}

// ── Phase 9: Public API & Pipeline Types ─────────────────────────────────────

export interface ApiKey {
  id:             number
  name:           string
  owner_id:       string | null
  scopes:         string[]
  rate_limit_rph: number
  last_used_at:   string | null
  expires_at:     string | null
  created_at:     string
  raw_key?:       string  // only present on creation response
}

export interface WebhookRecord {
  id:         number
  name:       string
  url:        string
  events:     string[]
  active:     boolean
  created_at: string
  secret?:    string  // only present on creation response
}

export interface WebhookDelivery {
  id:              number
  webhook_id:      number
  event_type:      string
  status:          'pending' | 'success' | 'failed'
  response_status: number | null
  attempt_count:   number
  delivered_at:    string | null
  created_at:      string
}

// ── User Accounts (Sections 7-9) ──────────────────────────────────────────────

export interface CmsUserRole {
  role:   string
  scope?: string
}

export interface CmsUser {
  id:                   number
  email:                string
  name:                 string | null
  role:                 string
  is_active:            number   // 0 | 1
  is_locked:            number   // 0 | 1
  mfa_enabled:          number   // 0 | 1
  force_password_reset: number   // 0 | 1
  last_login_at:        string | null
  locked_at:            string | null
  locked_by:            string | null
  sessions_revoked_at:  string | null
  created_at:           string
  updated_at:           string | null
  updated_by:           string | null
  // Part 3 Section 12: entitlements
  idp_subject_id: string | null
  entitlements:   string[]
  cms_roles:      CmsUserRole[]
}

export interface DirectoryUser {
  id:             number
  email:          string
  name:           string | null
  idp_subject_id: string | null
  entitlements:   string[]
  role:           string
}

export interface GrantCmsAccessRequest {
  email:          string
  idp_subject_id?: string
  initial_role:   string
}

export interface CmsUserListResponse {
  users: CmsUser[]
  total: number
}

export interface UserSessionRecord {
  id:               number
  user_email:       string
  login_at:         string
  logout_at:        string | null
  duration_seconds: number | null
  ip_address:       string | null
  user_agent:       string | null
  device_parsed:    string | null  // JSON: {browser, os}
  auth_method:      string
  mfa_satisfied:    number         // 0 | 1
  revoked_at:       string | null
  revoked_by:       string | null
}

export interface UserSessionsResponse {
  sessions: UserSessionRecord[]
  total:    number
}

export interface UserActivitySummary {
  content_created:    number
  content_edited:     number
  reviews_performed:  number
  publish_actions:    number
  automation_jobs:    number
  prompts_referenced: number
}

// ── Part 4 Section 3: Portal Engine Types ──────────────────────────────────

export interface PortalSelectionRule {
  id: string
  site_id: number
  taxonomy_node_id: number | null
  rule_type: string
  percentage: number
  min_items: number
  max_items: number
  content_type_filter: string[]
  exclude_if_older_than_days: number | null
  boost_recent_days: number
  boost_editorial: number
  created_by: number | null
  created_at: string
  updated_at: string
}

export interface PortalPage {
  id: string
  site_id: number
  portal_type: string
  taxonomy_node_id: number | null
  portal_date: string
  status: 'active' | 'archived' | 'draft' | 'superseded'
  generated_by: number | null
  content_ids: string[]
  generated_at: string
  item_count: number
  metadata: Record<string, unknown>
  generation_method: 'manual' | 'auto_on_demand' | 'scheduled'
  hit_count: number
}

export interface PortalHitTimeseries {
  portal_id: string
  hour_bucket: string
  hit_count: number
}

// Part 4 S7–8: Portal workspace types
export interface PortalSite {
  site_id: number
  site_name: string | null
}

export interface PortalGridRow {
  id: string
  site_id: number
  portal_type: string
  taxonomy_node_id: number | null
  taxonomy_name: string | null
  portal_date: string
  item_count: number
  hit_count: number
  generated_at: string
  generation_method: 'manual' | 'auto_on_demand' | 'scheduled'
  status: 'active' | 'superseded' | 'archived' | 'draft'
}

export interface PortalDetailItem {
  id: string
  title: string
  excerpt: string | null
  cached_image_path: string | null
  image_url: string | null
  published_at: string | null
}

export interface PortalDetail extends PortalPage {
  taxonomy_name: string | null
  items: PortalDetailItem[]
  timeseries: PortalHitTimeseries[]
}

// Part 4 S9–11: Websites Module
export interface WebsiteTaxonomyAssignment {
  id: string
  site_id: string
  taxonomy_node_id: number
  display_order: number
  is_featured: boolean
  custom_label: string | null
  nav_position: 'primary_nav' | 'secondary_nav' | 'footer_nav' | 'sidebar' | 'hidden'
  assigned_at: string
  assigned_by: string | null
  // joined from jv_taxonomy
  name: string
  slug: string
}

export interface WebsitePage {
  id: string
  site_id: string
  page_slug: string
  page_title: string
  body_html: string | null
  body_markdown: string | null
  seo_metadata: Record<string, unknown>
  nav_position: string
  display_order: number
  status: 'draft' | 'published' | 'archived'
  version: number
  created_at: string
  updated_at: string
}

export interface WebsitePackage {
  id: string
  site_id: string
  version_number: string
  build_timestamp: string
  config_snapshot: Record<string, unknown>
  taxonomy_snapshot: WebsiteTaxonomyAssignment[]
  file_size_bytes: number
  storage_url: string | null
  cdn_download_url: string | null
  checksum_sha256: string | null
  release_notes: string | null
  built_by: string | null
  status: 'building' | 'ready' | 'failed' | 'deprecated'
  created_at: string
  // Part 5 S4: Satellite deployment metadata
  runtime_version: string | null
  sync_engine_version: string | null
  wizard_included: boolean
  content_snapshot_at: string | null
  content_object_count: number
  yaml_schema_version: string | null
  min_node_version: string | null
  deployment_targets: string[]
}

// Part 5 S8: Incremental update records
export interface SatelliteUpdate {
  id: string
  site_id: string
  update_version: string
  update_type: 'content_change' | 'taxonomy_change' | 'theme_change' | 'config_change' | 'runtime_patch' | 'mixed'
  min_package_version: string | null
  changed_objects: Array<{ object_id: string; object_type: string; action: 'created' | 'updated' | 'deleted'; version_before?: number; version_after?: number }>
  scope_summary: string | null
  payload_size_bytes: number
  payload_url: string | null
  payload_checksum: string | null
  release_notes: string | null
  status: 'queued' | 'building' | 'ready' | 'failed' | 'superseded'
  created_at: string
  created_by: string | null
}

// Part 5 S11: Satellite sync status
export interface SatelliteSyncStatus {
  site_id: string
  last_check_at: string | null
  last_sync_at: string | null
  current_package_version: string | null
  current_update_version: string | null
  sync_status: 'in_sync' | 'behind' | 'error' | 'unknown'
  consecutive_failures: number
  last_error: string | null
  ip_address: string | null
  updated_at: string
  pending_updates?: number
}

// Part 5 S15: Image generation job lifecycle
export interface ImageGenerationJob {
  id: string
  content_object_id: string
  site_id: string | null
  prompt_context: string | null
  style_constraints: Record<string, unknown>
  aspect_ratio: string
  resolution: { width: number; height: number }
  gpu_job_status: 'submitted' | 'processing' | 'completed' | 'failed' | 'timed_out'
  gpu_response: Record<string, unknown> | null
  image_asset_id: string | null
  image_url: string | null
  image_status: 'pending' | 'generating' | 'in_review' | 'approved' | 'rejected' | 'archived'
  reviewer_id: string | null
  checked_out_at: string | null
  approved_by: string | null
  approved_at: string | null
  rejected_by: string | null
  rejected_at: string | null
  rejection_reason: string | null
  requested_by: string | null
  retry_count: number
  previous_job_id: string | null
  created_at: string
  updated_at: string
  // joined fields
  content_title?: string
  taxonomy_name?: string
}

// Part 4 S12–14
export interface PortalRules {
  content_types?: string[]
  min_pool_size?: number
  recency_days?: number
  editorial_weight?: number
  max_per_author?: number
}

export interface ContentRevisionSummary {
  id: number
  version: number
  change_summary: string | null
  changed_by: string | null
  changed_at: string
}

// ── Part 6: Server Nodes ──────────────────────────────────────────────────────

export interface ServerNode {
  id: string
  node_name: string
  environment: 'production' | 'staging' | 'development'
  region: string | null
  base_url: string | null
  internal_sync_endpoint: string | null
  database_role: 'primary' | 'replica' | 'read_replica'
  software_version: string | null
  last_heartbeat_at: string | null
  health_status: 'healthy' | 'degraded' | 'unreachable' | 'maintenance' | 'unknown'
  cache_status: 'current' | 'stale' | 'rebuilding' | 'error' | 'unknown'
  replication_lag_ms: number | null
  pending_sync_count: number
  last_sync_at: string | null
  config: Record<string, unknown>
  is_active: boolean
  registered_at: string
  registered_by: string | null
  updated_at: string
}

// ── Part 6: Audit Reports ─────────────────────────────────────────────────────

export interface AuditScores {
  scriptural_accuracy?: number
  doctrinal_clarity?: number
  pastoral_tone?: number
  misinterpretation_risk?: number
  sin_promotion?: number
  worship_integrity?: number
  composite?: number
}

export interface AuditFinding {
  category: string
  severity: 'critical' | 'warning' | 'info'
  excerpt: string
  explanation: string
  line_reference?: string
}

export interface AuditReport {
  id: string
  object_id: string
  object_version: number | null
  audit_type: 'doctrinal' | 'image_safety' | 'lyrics' | 'composite'
  rubric_id: string | null
  rubric_version: number | null
  model_id: string | null
  model_config: Record<string, unknown> | null
  audit_language: string
  prompt_text: string | null
  scores: AuditScores
  findings: AuditFinding[]
  result: 'pending' | 'passed' | 'passed_with_warnings' | 'failed'
  audited_at: string
  // joined
  rubric_name?: string
  // queue-join fields
  title?: string
  object_type?: string
  status?: string
  audit_status?: string
  audit_score?: number
  audit_result?: string
  submitted_for_review_at?: string | null
}

export interface AuditRubric {
  id: string
  name: string
  rubric_type: 'doctrinal' | 'image_safety' | 'lyrics'
  version: number
  is_global: boolean
  site_id: string | null
  content_types: string[]
  scoring_weights: Record<string, number>
  system_prompt: string | null
  evaluation_prompt: string | null
  pass_threshold: number
  warning_threshold: number
  is_active: boolean
  created_by: string | null
  created_at: string
  updated_at: string
}

export interface SelfTestResult {
  id: string
  test_suite: string
  test_name: string
  result: 'passed' | 'failed' | 'error' | 'skipped' | 'pending'
  expected_value: string | null
  actual_value: string | null
  error_message: string | null
  remediation: string | null
  run_id: string
  triggered_by: 'scheduled' | 'deployment' | 'manual'
  triggered_by_user: string | null
  duration_ms: number | null
  created_at: string
}

export interface PropagationLog {
  id: string
  object_id: string
  object_type: string | null
  node_id: string
  action: string
  composite_checksum: string | null
  status: 'pending' | 'synced' | 'failed' | 'skipped'
  response_status: number | null
  checksum_verified: boolean | null
  error_message: string | null
  retry_count: number
  created_at: string
  completed_at: string | null
}

export interface TaxonomyChecksum {
  taxonomy_node_id: number
  membership_checksum: string
  content_inventory_checksum: string
  last_computed_at: string
  object_count: number
}
